train_file: ['/home/data/finetune_subset.json']
             
test_file: ['/home/data/test_subset.json']
# answer_list: 'data/answer_list.json'

vqa_root: '/home/data/'

image_res: 224
k_test: 128

batch_size_train: 16 
batch_size_test: 16 
epochs: 4
learning_rate: 0.00005

save_freq: 100
save_dir: './saved_models/'

# load_path: './saved_models/20-May_23-21-15/epoch_1_iter_1200.pt'
load_path: False

alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'


# visualbert
num_hidden_layers: 2
num_attention_heads: 4
max_position_embeddings: 128

# optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
# schedular: {sched: cosine, lr: 2e-5, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}
